//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServerAndWebSocketClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketD2
    {
        public int ID { get; set; }
        public string Serial { get; set; }
        public long Packet { get; set; }
    }
}
