//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServerAndWebSocketClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setting()
        {
            this.Data = new HashSet<Datum>();
        }
    
        public string Serial { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string Unit { get; set; }
        public bool Celsius { get; set; }
        public byte Delay { get; set; }
        public string Starttime { get; set; }
        public string Stoptime { get; set; }
        public string Settingtime { get; set; }
        public int DurationDay { get; set; }
        public byte DurationHour { get; set; }
        public byte IntervalSec { get; set; }
        public byte IntervalMin { get; set; }
        public byte IntervalHour { get; set; }
        public bool ContinueMem { get; set; }
        public bool Stopkey { get; set; }
        public bool AutoStart { get; set; }
        public byte IntervalSendLoraMin { get; set; }
        public byte IntervalSendLoraHour { get; set; }
        public byte IntervalSendLoraDay { get; set; }
        public byte Devicetype { get; set; }
        public string TimezoneId { get; set; }
        public string FirmwareVer { get; set; }
        public bool SettingByLora { get; set; }
        public short ContinueMemoryCount { get; set; }
        public Nullable<byte> NumberOfMeasD0 { get; set; }
        public Nullable<byte> NumberOfMeasD1 { get; set; }
    
        public virtual Alarm Alarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datum> Data { get; set; }
        public virtual Realtime Realtime { get; set; }
    }
}
