//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServerAndWebSocketClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int ID { get; set; }
        public string Serial { get; set; }
        public double Data1 { get; set; }
        public double Data2 { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Setting Setting { get; set; }
    }
}
