//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServerAndWebSocketClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pexo63LorawanEntities : DbContext
    {
        public Pexo63LorawanEntities()
            : base("name=Pexo63LorawanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm> Alarms { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Realtime> Realtimes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
