//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPServerAndWebSocketClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setting()
        {
            this.Data = new HashSet<Data>();
        }
    
        public string Serial { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Delay { get; set; }
        public string Starttime { get; set; }
        public string Stoptime { get; set; }
        public string Settingtime { get; set; }
        public string Duration { get; set; }
        public string Interval { get; set; }
        public double HighAlarmTemp { get; set; }
        public double LowAlarmTemp { get; set; }
        public Nullable<double> HighAlarmHumid { get; set; }
        public Nullable<double> LowAlarmHumid { get; set; }
        public bool AlarmStatus { get; set; }
        public string FirmwareVer { get; set; }
    
        public virtual Alarm Alarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data> Data { get; set; }
        public virtual Realtime Realtime { get; set; }
    }
}
