//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxithermalWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtime
    {
        public string Serial { get; set; }
        public string Status { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Runtime { get; set; }
        public string TimeUpdated { get; set; }
    
        public virtual Setting Setting { get; set; }
    }
}
